### PR TITLE
fixNVDALoading

### PR DESCRIPTION
**Pull request by ABuffEr**
Hi,

working on [an updated script](https://github.com/ABuffEr/kodiSRInstallerScript) to install Kodi Screen Reader on Windows, I investigated and solved the problems that was preventing NVDA to be available as TTS engine (particularly in Kodi 64-bit).

I use your 2to3 branch as backends reference in script above, so I'll very happy if you accept this PR. And, with me, a lots of blind users, I think :)

### CODE REVIEW

**Comment by ABuffEr** [comment]
Sorry, I don't know why it went out a PR against the master branch, my intention is to do against 2to3... I can redo if you want.

**Comment by pvagner** [comment]
Hello,
Thanks for looking into this it's a while since I've tested it on windows.
I will review, test and merge it next week as I am traveling these days.

**Comment by ABuffEr** [comment]
Hi,
any news? :)

**Comment by pvagner** [comment]
Finally I managed to cherry-pick the needed commit.
I apologize for waiting so long.

**Pull request closed without merging**
